name: random-video-chat-app
region: nyc
services:
  - name: signaling
    environment_slug: node-js
    source_dir: /
    http_port: 3000
    instance_size_slug: basic-xs
    instance_count: 2 # run 2 instances; Redis adapter handles cross-instance
    routes:
      - path: /
    health_check:
      http_path: /healthz
    build_command: "npm ci"
    run_command: "npm start"
    envs:
      - key: REDIS_URL
        type: SECRET
        scope: RUN_AND_BUILD_TIME # you'll enter this once in DO UI
      - key: NODE_ENV
        value: production
        scope: RUN_AND_BUILD_TIME
      - key: ADMIN_KEY
        type: SECRET
        scope: RUN_AND_BUILD_TIME # Strong random key for admin API access
      - key: ALLOWED_ORIGINS
        value: "http://localhost:3000,https://random-video-chat-rose.vercel.app"
        scope: RUN_AND_BUILD_TIME
